# Generated by Django 3.0.4 on 2020-03-13 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('idPerson', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('idProject', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('idNotification', models.AutoField(primary_key=True, serialize=False)),
                ('what', models.CharField(max_length=100)),
                ('projectOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Project')),
                ('who', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Person')),
            ],
        ),
    ]
