# Generated by Django 3.0.4 on 2020-03-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200325_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
