# Generated by Django 3.0.4 on 2020-03-25 21:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person2',
            new_name='Person',
        ),
    ]
