# Generated by Django 3.0.4 on 2020-03-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
