# Generated by Django 3.0.4 on 2020-03-26 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 20, 34, 55, 933133, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 20, 34, 55, 933133, tzinfo=utc)),
        ),
    ]
