# Generated by Django 3.0.4 on 2020-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200326_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
